/**
 * fetchTop400BinanceUniverse.js
 * 
 * Builds the top-400 crypto universe from Binance USDT spot pairs.
 * Ensures that all currently active pairs from crypto_long and crypto_short are explicitly included.
 * 
 * Output: bot/universes/crypto_top400.js
 * 
 * Usage: node scripts/fetchTop400BinanceUniverse.js
 */

import axios from "axios";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { CRYPTO_LONG } from "../bot/universes/crypto_long.js";
import { CRYPTO_SHORT } from "../bot/universes/crypto_short.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const OUTPUT_FILE = path.join(__dirname, "..", "bot", "universes", "crypto_top400.js");

const STABLECOIN_BLACKLIST = new Set([
    "USDC", "BUSD", "TUSD", "USDP", "DAI", "FDUSD", "USDD", "USD1", "USDE", "PYUSD",
    "EURT", "EUROC", "EURC", "PAXG", "XAUT",
    "WBTC", "WBETH", "STETH", "CBETH", "RETH", "LBETH", "METH",
    "BTTC", "BTT",
]);

async function main() {
    console.log("Fetching Binance 24h tickers...");
    const res = await axios.get("https://api.binance.com/api/v3/ticker/24hr");

    let usdtPairs = res.data
        .filter(t => t.symbol.endsWith("USDT"))
        .filter(t => {
            const base = t.symbol.replace("USDT", "");
            return !STABLECOIN_BLACKLIST.has(base);
        })
        .map(t => ({
            symbol: t.symbol,
            base: t.symbol.replace("USDT", ""),
            volume24hUSD: parseFloat(t.quoteVolume),
        }))
        .filter(t => t.volume24hUSD > 0)
        .sort((a, b) => b.volume24hUSD - a.volume24hUSD);

    // Get current active symbols
    const activeSymbols = new Set([
        ...CRYPTO_LONG.map(s => s.replace("B-", "")),
        ...CRYPTO_SHORT.map(s => s.replace("B-", ""))
    ]);
    
    // We want to select top 400. And ensure activeSymbols are in there.
    const selected = [];
    const selectedSet = new Set();
    
    // First, force add active symbols if they exist in usdtPairs
    for (const pair of usdtPairs) {
        if (activeSymbols.has(pair.symbol)) {
            selected.push(pair);
            selectedSet.add(pair.symbol);
        }
    }
    
    // Then fill the rest up to 400 total
    for (const pair of usdtPairs) {
        if (selected.length >= 400) break;
        if (!selectedSet.has(pair.symbol)) {
            selected.push(pair);
            selectedSet.add(pair.symbol);
        }
    }
    
    // Finally sort them by volume again just to be neat
    selected.sort((a, b) => b.volume24hUSD - a.volume24hUSD);

    console.log(`Selected ${selected.length} pairs.`);
    const symbols = selected.map(p => `B-${p.symbol}`);
    const bases = selected.map(p => p.base);

    const fileContent = `// bot/universes/crypto_top400.js
// Auto-generated by scripts/fetchTop400BinanceUniverse.js
// Generated: ${new Date().toISOString()}
// Source: Binance Top 400 USDT pairs by 24h volume (includes currently active pairs)
// Total: ${symbols.length} pairs

export const CRYPTO_TOP400 = [
${symbols.map(s => `  "${s}"`).join(",\n")}
];

export const CRYPTO_TOP400_BASES = [
${bases.map(b => `  "${b}"`).join(",\n")}
];
`;

    fs.writeFileSync(OUTPUT_FILE, fileContent);
    console.log(`Written to: ${OUTPUT_FILE}`);
}

main().catch(err => {
    console.error("❌ Fatal error:", err.message);
    process.exit(1);
});
