/**
 * fetchTop100Universe.js
 * 
 * Builds the top-100 crypto universe as intersection of:
 *   1. Binance USDT spot pairs (ranked by 24h volume)
 *   2. CoinDCX active USDT markets
 * 
 * Output: bot/universes/crypto_top100.js
 * 
 * Usage: node scripts/fetchTop100Universe.js
 */

import axios from "axios";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const OUTPUT_FILE = path.join(__dirname, "..", "bot", "universes", "crypto_top100.js");

// Stablecoins, wrapped/pegged tokens to exclude (they don't trend)
const STABLECOIN_BLACKLIST = new Set([
    // USD stablecoins
    "USDC", "BUSD", "TUSD", "USDP", "DAI", "FDUSD", "USDD", "USD1", "USDE", "PYUSD",
    // EUR stablecoins
    "EURT", "EUROC", "EURC",
    // Gold / commodity pegged
    "PAXG", "XAUT",
    // Wrapped / staked versions
    "WBTC", "WBETH", "STETH", "CBETH", "RETH", "LBETH", "METH",
    // Dust / spam
    "BTTC", "BTT",
]);

async function fetchBinanceUSDT() {
    console.log("[1/3] Fetching Binance 24h tickers...");
    const res = await axios.get("https://api.binance.com/api/v3/ticker/24hr");

    const usdtPairs = res.data
        .filter(t => t.symbol.endsWith("USDT"))
        .filter(t => {
            const base = t.symbol.replace("USDT", "");
            return !STABLECOIN_BLACKLIST.has(base);
        })
        .map(t => ({
            symbol: t.symbol,
            base: t.symbol.replace("USDT", ""),
            volume24hUSD: parseFloat(t.quoteVolume), // USDT volume
        }))
        .filter(t => t.volume24hUSD > 0)
        .sort((a, b) => b.volume24hUSD - a.volume24hUSD);

    console.log(`   Found ${usdtPairs.length} USDT pairs on Binance`);
    return usdtPairs;
}

async function fetchCoinDCXMarkets() {
    console.log("[2/3] Fetching CoinDCX markets...");
    const res = await axios.get("https://api.coindcx.com/exchange/v1/markets");

    const usdtBases = new Set(
        res.data
            .filter(m => typeof m === "string" && m.endsWith("USDT"))
            .map(m => m.replace("USDT", ""))
    );

    // Fallback: if response is objects with 'pair' field
    if (usdtBases.size === 0 && res.data.length > 0 && typeof res.data[0] === "object") {
        for (const m of res.data) {
            const sym = m.symbol || m.pair || m.market || "";
            if (sym.endsWith("USDT")) {
                usdtBases.add(sym.replace("USDT", ""));
            }
        }
    }

    console.log(`   Found ${usdtBases.size} USDT bases on CoinDCX`);
    return usdtBases;
}

async function main() {
    console.log("╔══════════════════════════════════════════════╗");
    console.log("║  🌍  TOP 100 CRYPTO UNIVERSE BUILDER        ║");
    console.log("╚══════════════════════════════════════════════╝\n");

    // 1. Fetch from both exchanges
    const binancePairs = await fetchBinanceUSDT();
    const coindcxBases = await fetchCoinDCXMarkets();

    // 2. Intersect: only pairs on BOTH exchanges
    console.log("\n[3/3] Computing intersection (Binance ∩ CoinDCX)...");
    const intersection = binancePairs.filter(p => coindcxBases.has(p.base));

    console.log(`   Intersection: ${intersection.length} pairs available on both`);

    // 3. Take top 100 by volume
    const top100 = intersection.slice(0, 100);

    console.log(`\n✅ TOP ${top100.length} UNIVERSE (by 24h USD volume):\n`);
    top100.forEach((p, i) => {
        const volM = (p.volume24hUSD / 1e6).toFixed(1);
        console.log(`  ${String(i + 1).padStart(3)}. ${p.base.padEnd(8)} $${volM}M`);
    });

    // 4. Generate output file
    const symbols = top100.map(p => `B-${p.symbol}`);
    const bases = top100.map(p => p.base);

    const fileContent = `// bot/universes/crypto_top100.js
// Auto-generated by scripts/fetchTop100Universe.js
// Generated: ${new Date().toISOString()}
// Source: Binance 24h volume ∩ CoinDCX active markets
// Total: ${symbols.length} pairs

export const CRYPTO_TOP100 = [
${symbols.map(s => `  "${s}"`).join(",\n")}
];

// Base coin names (for display / logging)
export const CRYPTO_TOP100_BASES = [
${bases.map(b => `  "${b}"`).join(",\n")}
];
`;

    fs.writeFileSync(OUTPUT_FILE, fileContent);
    console.log(`\n📁 Written to: ${OUTPUT_FILE}`);
    console.log(`   ${symbols.length} pairs ready for backtesting`);

    // 5. Summary stats
    const totalVolume = top100.reduce((sum, p) => sum + p.volume24hUSD, 0);
    console.log(`\n📊 Total 24h volume: $${(totalVolume / 1e9).toFixed(2)}B`);
    console.log(`   Top 5: ${top100.slice(0, 5).map(p => p.base).join(", ")}`);
    console.log(`   Bottom 5: ${top100.slice(-5).map(p => p.base).join(", ")}`);
}

main().catch(err => {
    console.error("❌ Fatal error:", err.message);
    process.exit(1);
});
